CREATE OR REPLACE PROCEDURE admin.promote_process_run(p_process_run_id BIGINT) LANGUAGE plpgsql AS $$
DECLARE v_file_id BIGINT; v_report_id BIGINT; v_errors BIGINT;
BEGIN
 SELECT file_id INTO STRICT v_file_id FROM admin.process_execution_log WHERE process_run_id=p_process_run_id;
 SELECT COUNT(*) INTO v_errors FROM admin.data_quality_issue WHERE process_run_id=p_process_run_id AND severity IN('Error','Critical');
 IF v_errors>0 THEN RAISE EXCEPTION 'Run % has % blocking issues',p_process_run_id,v_errors; END IF;
 INSERT INTO raw.diagnostic_report(file_id,file_name,file_path,vin,sw_i_step,sa_codes) SELECT file_id,file_name,file_path,vin,sw_i_step,sa_codes FROM stage.diagnostic_report WHERE process_run_id=p_process_run_id ON CONFLICT(file_id) DO UPDATE SET file_path=EXCLUDED.file_path,vin=EXCLUDED.vin,sw_i_step=EXCLUDED.sw_i_step,sa_codes=EXCLUDED.sa_codes RETURNING report_id INTO v_report_id;
 INSERT INTO raw.ecu_version(report_id,ecu_name,hardware_version,bootloader_version,sw_version,coding,diagnostic_address,calibration_version,network,secure_boot,ota_state) SELECT v_report_id,ecu_name,hardware_version,bootloader_version,sw_version,coding,diagnostic_address,calibration_version,network,secure_boot,ota_state FROM stage.ecu_version WHERE process_run_id=p_process_run_id ON CONFLICT(report_id,ecu_name) DO UPDATE SET hardware_version=EXCLUDED.hardware_version,bootloader_version=EXCLUDED.bootloader_version,sw_version=EXCLUDED.sw_version,coding=EXCLUDED.coding,diagnostic_address=EXCLUDED.diagnostic_address,calibration_version=EXCLUDED.calibration_version,network=EXCLUDED.network,secure_boot=EXCLUDED.secure_boot,ota_state=EXCLUDED.ota_state;
 INSERT INTO raw.dtc_event(report_id,source_row_number,ecu_name,dtc_code,description,fault_category,status,occurrence_counter,aging_counter,priority,event_timestamp,risk_score) SELECT v_report_id,source_row_number,ecu_name,UPPER(dtc_code),description,fault_category,status,occurrence_counter,aging_counter,priority,event_timestamp,risk_score FROM stage.dtc_event WHERE process_run_id=p_process_run_id ON CONFLICT(report_id,source_row_number) DO UPDATE SET status=EXCLUDED.status,occurrence_counter=EXCLUDED.occurrence_counter,aging_counter=EXCLUDED.aging_counter,priority=EXCLUDED.priority,risk_score=EXCLUDED.risk_score;
 INSERT INTO raw.environment_signal(dtc_event_id,source_row_number,signal_name,signal_value,numeric_signal_value,event_timestamp) SELECT d.dtc_event_id,s.source_row_number,s.signal_name,s.signal_value,CASE WHEN BTRIM(s.signal_value)~'^-?[0-9]+([.][0-9]+)?$' THEN BTRIM(s.signal_value)::NUMERIC(18,4) END,s.event_timestamp FROM stage.environment_signal s JOIN raw.dtc_event d ON d.report_id=v_report_id AND d.ecu_name=s.ecu_name AND d.dtc_code=UPPER(s.dtc_code) AND d.event_timestamp=s.event_timestamp WHERE s.process_run_id=p_process_run_id ON CONFLICT(dtc_event_id,source_row_number) DO UPDATE SET signal_name=EXCLUDED.signal_name,signal_value=EXCLUDED.signal_value,numeric_signal_value=EXCLUDED.numeric_signal_value;
 UPDATE admin.process_execution_log SET end_time=CURRENT_TIMESTAMP,files_processed=1,report_records_loaded=(SELECT COUNT(*) FROM stage.diagnostic_report WHERE process_run_id=p_process_run_id),ecu_records_loaded=(SELECT COUNT(*) FROM stage.ecu_version WHERE process_run_id=p_process_run_id),dtc_records_loaded=(SELECT COUNT(*) FROM stage.dtc_event WHERE process_run_id=p_process_run_id),environment_records_loaded=(SELECT COUNT(*) FROM stage.environment_signal WHERE process_run_id=p_process_run_id),process_status='Completed' WHERE process_run_id=p_process_run_id;
 UPDATE admin.file_inventory SET processing_end_time=CURRENT_TIMESTAMP,process_status='Completed' WHERE file_id=v_file_id;
END $$;
